// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-njT6Xevp7LX6Hm4x-KsIENg-nhA_yE',
    appId: '1:408311919237:web:543a2d6e3c2974b4e32fec',
    messagingSenderId: '408311919237',
    projectId: 'pruebafirebase-af088',
    authDomain: 'pruebafirebase-af088.firebaseapp.com',
    storageBucket: 'pruebafirebase-af088.appspot.com',
    measurementId: 'G-TFKVNTQEHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_PFu40SkWl01UO8klE-kDIn5A1OzmiM',
    appId: '1:408311919237:android:972389ee516407d0e32fec',
    messagingSenderId: '408311919237',
    projectId: 'pruebafirebase-af088',
    storageBucket: 'pruebafirebase-af088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu727OfURQ1yWdordZh955egG6e5FdqOU',
    appId: '1:408311919237:ios:bb6a8fec0fd71d4de32fec',
    messagingSenderId: '408311919237',
    projectId: 'pruebafirebase-af088',
    storageBucket: 'pruebafirebase-af088.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu727OfURQ1yWdordZh955egG6e5FdqOU',
    appId: '1:408311919237:ios:54b271ddd1666517e32fec',
    messagingSenderId: '408311919237',
    projectId: 'pruebafirebase-af088',
    storageBucket: 'pruebafirebase-af088.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
